// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/luna.proto
// Protobuf C++ Version: 5.29.3

#include "proto/luna.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace luna {
              template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;

inline constexpr ButtonEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{0},
        value_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ButtonEvent::ButtonEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ButtonEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ButtonEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ButtonEventDefaultTypeInternal() {}
  union {
    ButtonEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ButtonEventDefaultTypeInternal _ButtonEvent_default_instance_;

inline constexpr AxisEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{0},
        value_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AxisEvent::AxisEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AxisEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AxisEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AxisEventDefaultTypeInternal() {}
  union {
    AxisEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AxisEventDefaultTypeInternal _AxisEvent_default_instance_;

inline constexpr ControllerEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : event_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR ControllerEvent::ControllerEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ControllerEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ControllerEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ControllerEventDefaultTypeInternal() {}
  union {
    ControllerEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ControllerEventDefaultTypeInternal _ControllerEvent_default_instance_;
}  // namespace luna
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_proto_2fluna_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_proto_2fluna_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fluna_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::luna::ControllerEvent, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::luna::ControllerEvent, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::luna::ControllerEvent, _impl_.event_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::luna::AxisEvent, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::luna::AxisEvent, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::luna::AxisEvent, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::luna::AxisEvent, _impl_.name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::luna::ButtonEvent, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::luna::ButtonEvent, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::luna::ButtonEvent, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::luna::ButtonEvent, _impl_.name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::luna::Empty, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::luna::ControllerEvent)},
        {11, -1, -1, sizeof(::luna::AxisEvent)},
        {22, -1, -1, sizeof(::luna::ButtonEvent)},
        {33, -1, -1, sizeof(::luna::Empty)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::luna::_ControllerEvent_default_instance_._instance,
    &::luna::_AxisEvent_default_instance_._instance,
    &::luna::_ButtonEvent_default_instance_._instance,
    &::luna::_Empty_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fluna_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020proto/luna.proto\022\004luna\"`\n\017ControllerEv"
    "ent\022\037\n\004axis\030\001 \001(\0132\017.luna.AxisEventH\000\022#\n\006"
    "button\030\002 \001(\0132\021.luna.ButtonEventH\000B\007\n\005eve"
    "nt\"6\n\tAxisEvent\022\014\n\004code\030\001 \001(\005\022\r\n\005value\030\002"
    " \001(\002\022\014\n\004name\030\003 \001(\t\"8\n\013ButtonEvent\022\014\n\004cod"
    "e\030\001 \001(\005\022\r\n\005value\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\"\007\n\005"
    "Empty2=\n\nController\022/\n\tSendEvent\022\025.luna."
    "ControllerEvent\032\013.luna.Emptyb\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2fluna_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fluna_2eproto = {
    false,
    false,
    316,
    descriptor_table_protodef_proto_2fluna_2eproto,
    "proto/luna.proto",
    &descriptor_table_proto_2fluna_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_proto_2fluna_2eproto::offsets,
    file_level_enum_descriptors_proto_2fluna_2eproto,
    file_level_service_descriptors_proto_2fluna_2eproto,
};
namespace luna {
// ===================================================================

class ControllerEvent::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::luna::ControllerEvent, _impl_._oneof_case_);
};

void ControllerEvent::set_allocated_axis(::luna::AxisEvent* axis) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_event();
  if (axis) {
    ::google::protobuf::Arena* submessage_arena = axis->GetArena();
    if (message_arena != submessage_arena) {
      axis = ::google::protobuf::internal::GetOwnedMessage(message_arena, axis, submessage_arena);
    }
    set_has_axis();
    _impl_.event_.axis_ = axis;
  }
  // @@protoc_insertion_point(field_set_allocated:luna.ControllerEvent.axis)
}
void ControllerEvent::set_allocated_button(::luna::ButtonEvent* button) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_event();
  if (button) {
    ::google::protobuf::Arena* submessage_arena = button->GetArena();
    if (message_arena != submessage_arena) {
      button = ::google::protobuf::internal::GetOwnedMessage(message_arena, button, submessage_arena);
    }
    set_has_button();
    _impl_.event_.button_ = button;
  }
  // @@protoc_insertion_point(field_set_allocated:luna.ControllerEvent.button)
}
ControllerEvent::ControllerEvent(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:luna.ControllerEvent)
}
inline PROTOBUF_NDEBUG_INLINE ControllerEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::luna::ControllerEvent& from_msg)
      : event_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

ControllerEvent::ControllerEvent(
    ::google::protobuf::Arena* arena,
    const ControllerEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ControllerEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (event_case()) {
    case EVENT_NOT_SET:
      break;
      case kAxis:
        _impl_.event_.axis_ = ::google::protobuf::Message::CopyConstruct<::luna::AxisEvent>(arena, *from._impl_.event_.axis_);
        break;
      case kButton:
        _impl_.event_.button_ = ::google::protobuf::Message::CopyConstruct<::luna::ButtonEvent>(arena, *from._impl_.event_.button_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:luna.ControllerEvent)
}
inline PROTOBUF_NDEBUG_INLINE ControllerEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : event_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void ControllerEvent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ControllerEvent::~ControllerEvent() {
  // @@protoc_insertion_point(destructor:luna.ControllerEvent)
  SharedDtor(*this);
}
inline void ControllerEvent::SharedDtor(MessageLite& self) {
  ControllerEvent& this_ = static_cast<ControllerEvent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_event()) {
    this_.clear_event();
  }
  this_._impl_.~Impl_();
}

void ControllerEvent::clear_event() {
// @@protoc_insertion_point(one_of_clear_start:luna.ControllerEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (event_case()) {
    case kAxis: {
      if (GetArena() == nullptr) {
        delete _impl_.event_.axis_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.event_.axis_);
      }
      break;
    }
    case kButton: {
      if (GetArena() == nullptr) {
        delete _impl_.event_.button_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.event_.button_);
      }
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = EVENT_NOT_SET;
}


inline void* ControllerEvent::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ControllerEvent(arena);
}
constexpr auto ControllerEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ControllerEvent),
                                            alignof(ControllerEvent));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ControllerEvent::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ControllerEvent_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ControllerEvent::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ControllerEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ControllerEvent::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ControllerEvent>(), &ControllerEvent::ByteSizeLong,
            &ControllerEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ControllerEvent, _impl_._cached_size_),
        false,
    },
    &ControllerEvent::kDescriptorMethods,
    &descriptor_table_proto_2fluna_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ControllerEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> ControllerEvent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::luna::ControllerEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .luna.AxisEvent axis = 1;
    {PROTOBUF_FIELD_OFFSET(ControllerEvent, _impl_.event_.axis_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .luna.ButtonEvent button = 2;
    {PROTOBUF_FIELD_OFFSET(ControllerEvent, _impl_.event_.button_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::luna::AxisEvent>()},
    {::_pbi::TcParser::GetTable<::luna::ButtonEvent>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ControllerEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:luna.ControllerEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_event();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ControllerEvent::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ControllerEvent& this_ = static_cast<const ControllerEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ControllerEvent::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ControllerEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:luna.ControllerEvent)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          switch (this_.event_case()) {
            case kAxis: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1, *this_._impl_.event_.axis_, this_._impl_.event_.axis_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kButton: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.event_.button_, this_._impl_.event_.button_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:luna.ControllerEvent)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ControllerEvent::ByteSizeLong(const MessageLite& base) {
          const ControllerEvent& this_ = static_cast<const ControllerEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ControllerEvent::ByteSizeLong() const {
          const ControllerEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:luna.ControllerEvent)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          switch (this_.event_case()) {
            // .luna.AxisEvent axis = 1;
            case kAxis: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.event_.axis_);
              break;
            }
            // .luna.ButtonEvent button = 2;
            case kButton: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.event_.button_);
              break;
            }
            case EVENT_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ControllerEvent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ControllerEvent*>(&to_msg);
  auto& from = static_cast<const ControllerEvent&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:luna.ControllerEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_event();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kAxis: {
        if (oneof_needs_init) {
          _this->_impl_.event_.axis_ =
              ::google::protobuf::Message::CopyConstruct<::luna::AxisEvent>(arena, *from._impl_.event_.axis_);
        } else {
          _this->_impl_.event_.axis_->MergeFrom(from._internal_axis());
        }
        break;
      }
      case kButton: {
        if (oneof_needs_init) {
          _this->_impl_.event_.button_ =
              ::google::protobuf::Message::CopyConstruct<::luna::ButtonEvent>(arena, *from._impl_.event_.button_);
        } else {
          _this->_impl_.event_.button_->MergeFrom(from._internal_button());
        }
        break;
      }
      case EVENT_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ControllerEvent::CopyFrom(const ControllerEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:luna.ControllerEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ControllerEvent::InternalSwap(ControllerEvent* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.event_, other->_impl_.event_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata ControllerEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AxisEvent::_Internal {
 public:
};

AxisEvent::AxisEvent(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:luna.AxisEvent)
}
inline PROTOBUF_NDEBUG_INLINE AxisEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::luna::AxisEvent& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

AxisEvent::AxisEvent(
    ::google::protobuf::Arena* arena,
    const AxisEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AxisEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, code_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, code_),
           offsetof(Impl_, value_) -
               offsetof(Impl_, code_) +
               sizeof(Impl_::value_));

  // @@protoc_insertion_point(copy_constructor:luna.AxisEvent)
}
inline PROTOBUF_NDEBUG_INLINE AxisEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void AxisEvent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, code_),
           0,
           offsetof(Impl_, value_) -
               offsetof(Impl_, code_) +
               sizeof(Impl_::value_));
}
AxisEvent::~AxisEvent() {
  // @@protoc_insertion_point(destructor:luna.AxisEvent)
  SharedDtor(*this);
}
inline void AxisEvent::SharedDtor(MessageLite& self) {
  AxisEvent& this_ = static_cast<AxisEvent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* AxisEvent::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AxisEvent(arena);
}
constexpr auto AxisEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AxisEvent),
                                            alignof(AxisEvent));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AxisEvent::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AxisEvent_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AxisEvent::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AxisEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AxisEvent::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AxisEvent>(), &AxisEvent::ByteSizeLong,
            &AxisEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_._cached_size_),
        false,
    },
    &AxisEvent::kDescriptorMethods,
    &descriptor_table_proto_2fluna_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AxisEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 27, 2> AxisEvent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::luna::AxisEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AxisEvent, _impl_.code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_.code_)}},
    // float value = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_.value_)}},
    // string name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // float value = 2;
    {PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // string name = 3;
    {PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\0\4\0\0\0\0"
    "luna.AxisEvent"
    "name"
  }},
};

PROTOBUF_NOINLINE void AxisEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:luna.AxisEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.code_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.value_) -
      reinterpret_cast<char*>(&_impl_.code_)) + sizeof(_impl_.value_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AxisEvent::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AxisEvent& this_ = static_cast<const AxisEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AxisEvent::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AxisEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:luna.AxisEvent)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 code = 1;
          if (this_._internal_code() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_code(), target);
          }

          // float value = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_value()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_value(), target);
          }

          // string name = 3;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "luna.AxisEvent.name");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:luna.AxisEvent)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AxisEvent::ByteSizeLong(const MessageLite& base) {
          const AxisEvent& this_ = static_cast<const AxisEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AxisEvent::ByteSizeLong() const {
          const AxisEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:luna.AxisEvent)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 3;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // int32 code = 1;
            if (this_._internal_code() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_code());
            }
            // float value = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_value()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AxisEvent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AxisEvent*>(&to_msg);
  auto& from = static_cast<const AxisEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:luna.AxisEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_code() != 0) {
    _this->_impl_.code_ = from._impl_.code_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_value()) != 0) {
    _this->_impl_.value_ = from._impl_.value_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AxisEvent::CopyFrom(const AxisEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:luna.AxisEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AxisEvent::InternalSwap(AxisEvent* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_.value_)
      + sizeof(AxisEvent::_impl_.value_)
      - PROTOBUF_FIELD_OFFSET(AxisEvent, _impl_.code_)>(
          reinterpret_cast<char*>(&_impl_.code_),
          reinterpret_cast<char*>(&other->_impl_.code_));
}

::google::protobuf::Metadata AxisEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ButtonEvent::_Internal {
 public:
};

ButtonEvent::ButtonEvent(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:luna.ButtonEvent)
}
inline PROTOBUF_NDEBUG_INLINE ButtonEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::luna::ButtonEvent& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

ButtonEvent::ButtonEvent(
    ::google::protobuf::Arena* arena,
    const ButtonEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ButtonEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, code_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, code_),
           offsetof(Impl_, value_) -
               offsetof(Impl_, code_) +
               sizeof(Impl_::value_));

  // @@protoc_insertion_point(copy_constructor:luna.ButtonEvent)
}
inline PROTOBUF_NDEBUG_INLINE ButtonEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void ButtonEvent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, code_),
           0,
           offsetof(Impl_, value_) -
               offsetof(Impl_, code_) +
               sizeof(Impl_::value_));
}
ButtonEvent::~ButtonEvent() {
  // @@protoc_insertion_point(destructor:luna.ButtonEvent)
  SharedDtor(*this);
}
inline void ButtonEvent::SharedDtor(MessageLite& self) {
  ButtonEvent& this_ = static_cast<ButtonEvent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ButtonEvent::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ButtonEvent(arena);
}
constexpr auto ButtonEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ButtonEvent),
                                            alignof(ButtonEvent));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ButtonEvent::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ButtonEvent_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ButtonEvent::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ButtonEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ButtonEvent::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ButtonEvent>(), &ButtonEvent::ByteSizeLong,
            &ButtonEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_._cached_size_),
        false,
    },
    &ButtonEvent::kDescriptorMethods,
    &descriptor_table_proto_2fluna_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ButtonEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 29, 2> ButtonEvent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::luna::ButtonEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ButtonEvent, _impl_.code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_.code_)}},
    // int32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ButtonEvent, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_.value_)}},
    // string name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 value = 2;
    {PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string name = 3;
    {PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\0\0\4\0\0\0\0"
    "luna.ButtonEvent"
    "name"
  }},
};

PROTOBUF_NOINLINE void ButtonEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:luna.ButtonEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.code_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.value_) -
      reinterpret_cast<char*>(&_impl_.code_)) + sizeof(_impl_.value_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ButtonEvent::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ButtonEvent& this_ = static_cast<const ButtonEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ButtonEvent::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ButtonEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:luna.ButtonEvent)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 code = 1;
          if (this_._internal_code() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_code(), target);
          }

          // int32 value = 2;
          if (this_._internal_value() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_value(), target);
          }

          // string name = 3;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "luna.ButtonEvent.name");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:luna.ButtonEvent)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ButtonEvent::ByteSizeLong(const MessageLite& base) {
          const ButtonEvent& this_ = static_cast<const ButtonEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ButtonEvent::ByteSizeLong() const {
          const ButtonEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:luna.ButtonEvent)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 3;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // int32 code = 1;
            if (this_._internal_code() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_code());
            }
            // int32 value = 2;
            if (this_._internal_value() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_value());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ButtonEvent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ButtonEvent*>(&to_msg);
  auto& from = static_cast<const ButtonEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:luna.ButtonEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_code() != 0) {
    _this->_impl_.code_ = from._impl_.code_;
  }
  if (from._internal_value() != 0) {
    _this->_impl_.value_ = from._impl_.value_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ButtonEvent::CopyFrom(const ButtonEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:luna.ButtonEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ButtonEvent::InternalSwap(ButtonEvent* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_.value_)
      + sizeof(ButtonEvent::_impl_.value_)
      - PROTOBUF_FIELD_OFFSET(ButtonEvent, _impl_.code_)>(
          reinterpret_cast<char*>(&_impl_.code_),
          reinterpret_cast<char*>(&other->_impl_.code_));
}

::google::protobuf::Metadata ButtonEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:luna.Empty)
}
Empty::Empty(
    ::google::protobuf::Arena* arena,
    const Empty& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:luna.Empty)
}

inline void* Empty::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Empty(arena);
}
constexpr auto Empty::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Empty),
                                            alignof(Empty));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Empty::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Empty_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Empty::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Empty>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Empty::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Empty>(), &Empty::ByteSizeLong,
            &Empty::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Empty, _impl_._cached_size_),
        false,
    },
    &Empty::kDescriptorMethods,
    &descriptor_table_proto_2fluna_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Empty::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> Empty::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::luna::Empty>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata Empty::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace luna
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fluna_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
