// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/luna.proto
#ifndef GRPC_proto_2fluna_2eproto__INCLUDED
#define GRPC_proto_2fluna_2eproto__INCLUDED

#include "proto/luna.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace luna {

class Controller final {
 public:
  static constexpr char const* service_full_name() {
    return "luna.Controller";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::luna::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::luna::Empty>> AsyncSendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::luna::Empty>>(AsyncSendEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::luna::Empty>> PrepareAsyncSendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::luna::Empty>>(PrepareAsyncSendEventRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent* request, ::luna::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent* request, ::luna::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::luna::Empty>* AsyncSendEventRaw(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::luna::Empty>* PrepareAsyncSendEventRaw(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::luna::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::luna::Empty>> AsyncSendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::luna::Empty>>(AsyncSendEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::luna::Empty>> PrepareAsyncSendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::luna::Empty>>(PrepareAsyncSendEventRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent* request, ::luna::Empty* response, std::function<void(::grpc::Status)>) override;
      void SendEvent(::grpc::ClientContext* context, const ::luna::ControllerEvent* request, ::luna::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::luna::Empty>* AsyncSendEventRaw(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::luna::Empty>* PrepareAsyncSendEventRaw(::grpc::ClientContext* context, const ::luna::ControllerEvent& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendEvent_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendEvent(::grpc::ServerContext* context, const ::luna::ControllerEvent* request, ::luna::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendEvent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEvent(::grpc::ServerContext* /*context*/, const ::luna::ControllerEvent* /*request*/, ::luna::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendEvent(::grpc::ServerContext* context, ::luna::ControllerEvent* request, ::grpc::ServerAsyncResponseWriter< ::luna::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendEvent<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendEvent() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::luna::ControllerEvent, ::luna::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::luna::ControllerEvent* request, ::luna::Empty* response) { return this->SendEvent(context, request, response); }));}
    void SetMessageAllocatorFor_SendEvent(
        ::grpc::MessageAllocator< ::luna::ControllerEvent, ::luna::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::luna::ControllerEvent, ::luna::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEvent(::grpc::ServerContext* /*context*/, const ::luna::ControllerEvent* /*request*/, ::luna::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::luna::ControllerEvent* /*request*/, ::luna::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendEvent<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendEvent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEvent(::grpc::ServerContext* /*context*/, const ::luna::ControllerEvent* /*request*/, ::luna::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendEvent() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEvent(::grpc::ServerContext* /*context*/, const ::luna::ControllerEvent* /*request*/, ::luna::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendEvent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendEvent() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendEvent(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEvent(::grpc::ServerContext* /*context*/, const ::luna::ControllerEvent* /*request*/, ::luna::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendEvent() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::luna::ControllerEvent, ::luna::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::luna::ControllerEvent, ::luna::Empty>* streamer) {
                       return this->StreamedSendEvent(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendEvent(::grpc::ServerContext* /*context*/, const ::luna::ControllerEvent* /*request*/, ::luna::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendEvent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::luna::ControllerEvent,::luna::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendEvent<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendEvent<Service > StreamedService;
};

}  // namespace luna


#endif  // GRPC_proto_2fluna_2eproto__INCLUDED
